language: python
sudo: false
python:
 - "2.7"
 - "3.5"
 - "3.6"
addons:
  postgresql: "9.6"
env:
 - DJANGO_VERSION=1.10.4
 - DJANGO_VERSION=1.11.2
services:
 - redis-server
install:
 - pip install -q -rrequirements/base.txt
 - pip install -q -rrequirements/tests.txt
 - pip install -q Django==$DJANGO_VERSION
 - pip install coveralls
before_script:
 - createdb -E UTF-8 dash -U postgres -O $USER
script:
 - coverage run manage.py test --settings=dash_test_runner.settings_travis
 - flake8
after_success:
 - coveralls