# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 15:03
from __future__ import unicode_literals

import dash.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('dashblocks', '0006_auto_20140922_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashblockimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to=functools.partial(dash.utils.generate_file_path, *('dashblock_images',), **{}), width_field='width'),
        ),
    ]
