# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-17 08:09
from __future__ import unicode_literals

import dash.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('dashblocks', '0007_auto_20170116_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashblock',
            name='image',
            field=models.ImageField(blank=True, help_text='Any image that should be displayed with this content block, optional', null=True, upload_to=functools.partial(dash.utils.generate_file_path, *('dashblocks',), **{})),
        ),
    ]
