# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 15:03
from __future__ import unicode_literals

import dash.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0017_auto_20161026_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgbackground',
            name='image',
            field=models.ImageField(help_text='The image file', upload_to=functools.partial(dash.utils.generate_file_path, *('org_bgs',), **{})),
        ),
    ]
