# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-17 08:09
from __future__ import unicode_literals

import dash.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0018_auto_20170116_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='logo',
            field=models.ImageField(blank=True, help_text='The logo that should be used for this organization', null=True, upload_to=functools.partial(dash.utils.generate_file_path, *('logos',), **{})),
        ),
    ]
