# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0025_auto_20180322_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='country',
            field=models.ForeignKey(blank=True, help_text='The country organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_country', to='orgs.Org'),
        ),
        migrations.AddField(
            model_name='org',
            name='state',
            field=models.ForeignKey(blank=True, help_text='The state organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_state', to='orgs.Org'),
        ),
    ]
