# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 15:03
from __future__ import unicode_literals

import dash.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_story_written_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyimage',
            name='image',
            field=models.ImageField(help_text='The image file to use', upload_to=functools.partial(dash.utils.generate_file_path, *('stories',), **{})),
        ),
    ]
