# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-16 15:03
from __future__ import unicode_literals

import dash.utils
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20141008_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='An optional image that can describe this category', null=True, upload_to=functools.partial(dash.utils.generate_file_path, *('categories',), **{})),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(help_text='The image file to use', upload_to=functools.partial(dash.utils.generate_file_path, *('categories',), **{})),
        ),
    ]
